// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmployeeForm.Entity
{
    public partial class EmployeeDetail
    {
        public int Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Qualification { get; set; }
        public string Job_Role { get; set; }
        public int Experience { get; set; }
        public string Address { get; set; }
        public long Phone_No { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Conform_Password { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Created_Time_Stamp { get; set; }
        public DateTime Updated_Time_Stamp { get; set; }
    }
}